using System;
using System.Collections.Generic;
using System.IO;


namespace GHIBMS.Server.Pub
{

    /// <summary>
    /// linux操作系统基本操作辅助类
    /// </summary>
    public class LinuxOSHelper
    {
        #region 定义常量

        public static readonly string InterfaceTemplate = @"# interface file auto-generated by buildroot

        auto lo
        iface lo inet loopback

        auto eth0
        iface eth0 inet static
        address ${eth0_address}
        netmask ${eth0_netmask}
        gateway ${eth0_gateway}

        auto eth1
        iface eth1 inet static
        address ${eth1_address}
        netmask ${eth1_netmask}
        gateway ${eth1_gateway}
    ";

        #endregion

        #region 获取当前系统内核

        /// <summary>
        /// 获取当前系统内核
        /// </summary>
        /// <returns>返回系统内核信息</returns>
        public static string GetSystemCore()
        {
            string result = LinuxCommandHelper.RunCommand("uname", "-a");
            return result;
        }

        #endregion
 
        #region 获取系统本地时间

        /// <summary>
        /// 获取系统本地时间
        /// </summary>
        /// <returns>返回系统本地时间</returns>
        public static string GetLocaleDateTime()
        {
            string result = LinuxCommandHelper.RunCommand("date", "");
            return result;
        }

        #endregion

        #region 设置系统本地时间

        /// <summary>
        /// 设置系统本地时间
        /// </summary>
        /// <param name="datetimestr">要设置的时间</param>
        /// <returns>返回设置的时间</returns>
        public static string SetLocaleDateTime(string datetimestr)
        {
            string result = LinuxCommandHelper.RunCommand("date", $"-s \"{datetimestr}\"");
            LinuxCommandHelper.RunCommand("hwclock", "-w");
            return result;
        }

        #endregion

        #region 系统立即重启

        /// <summary>
        /// 系统立即重启
        /// </summary>
        /// <returns>返回执行结果</returns>
        public static string RebootNow()
        {
            string result = LinuxCommandHelper.RunCommand("reboot", "now");
            return result;
        }

        #endregion

        #region 系统重启

        /// <summary>
        /// 系统重启
        /// </summary>
        /// <returns>返回执行结果</returns>
        public static string Reboot()
        {
            string result = LinuxCommandHelper.RunCommand("reboot", "");
            return result;
        }

        #endregion
    }
    }
